#!/usr/bin/env python3
"""Prepare four-decimal float display for final MultiQC custom-data tables."""

from __future__ import annotations

import csv
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from pathlib import Path
import re
import argparse


FLOAT_RE = re.compile(
    r"""
    ^[+-]?
    (?:
        (?:\d+\.\d*) |
        (?:\.\d+) |
        (?:\d+(?:\.\d*)?[eE][+-]?\d+)
    )$
    """,
    re.VERBOSE,
)

QUANT = Decimal("0.0001")


def _format_cell(value: str) -> tuple[str, bool]:
    stripped = value.strip()
    if not stripped or not FLOAT_RE.match(stripped):
        return value, False
    try:
        decimal_value = Decimal(stripped)
    except InvalidOperation:
        return value, False
    if not decimal_value.is_finite():
        return value, False
    return format(decimal_value.quantize(QUANT, rounding=ROUND_HALF_UP), "f"), True


def _format_tsv(path: Path) -> tuple[bool, list[str]]:
    with path.open(newline="") as handle:
        rows = list(csv.reader(handle, delimiter="\t"))
    if not rows:
        return False, []

    changed = False
    float_columns = set()
    formatted_rows = [rows[0]]
    for row in rows[1:]:
        formatted_row = []
        for idx, cell in enumerate(row):
            formatted_cell, cell_changed = _format_cell(cell)
            changed = changed or cell_changed
            if cell_changed and idx < len(rows[0]):
                float_columns.add(rows[0][idx])
            formatted_row.append(formatted_cell)
        formatted_rows.append(formatted_row)

    if changed:
        with path.open("w", newline="") as handle:
            writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
            writer.writerows(formatted_rows)
    return changed, sorted(float_columns)


def _section_id(path: Path) -> str:
    name = path.name
    return name[:-8] if name.endswith("_mqc.tsv") else path.stem


def _write_format_config(path: Path, section_headers: dict[str, list[str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by workflow/scripts/format_multiqc_float_tables.py",
        "# Restricts final custom-data table float display to four decimal places.",
        "custom_data:",
    ]
    if not section_headers:
        lines.append("  {}")
    for section in sorted(section_headers):
        headers = section_headers[section]
        if not headers:
            continue
        lines.append(f"  {section}:")
        lines.append("    headers:")
        for header in headers:
            escaped = header.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'      "{escaped}":')
            lines.append('        format: "{:.4f}"')
    path.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", type=Path, help="Directory containing *_mqc.tsv files")
    parser.add_argument(
        "--format-config",
        type=Path,
        help="Write a MultiQC config overlay with four-decimal headers for inferred float columns",
    )
    args = parser.parse_args()

    changed_files = []
    section_headers = {}
    for path in sorted(args.root.rglob("*_mqc.tsv")):
        if not path.is_file():
            continue
        changed, float_columns = _format_tsv(path)
        if float_columns:
            section_headers[_section_id(path)] = float_columns
        if changed:
            changed_files.append(path)

    if args.format_config:
        _write_format_config(args.format_config, section_headers)

    print(f"formatted_float_tables={len(changed_files)}")
    print(f"float_format_sections={len(section_headers)}")
    for path in changed_files:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
