---
daylily:
  git_tag: 5.0.3
  git_repo: https://github.com/lsmc-bio/daylily-omics-analysis.git
  git_repo_ssh: git@github.com:lsmc-bio/daylily-omics-analysis.git
  analysis_root: /fsx/analysis_results/
  daylily_image_cmd: "test -s /fsx/references/runtime_assets/cached_envs/containers/c00914a60e21cceb34581232a917d832.simg"
  daylily_image_path: /fsx/references/runtime_assets/cached_envs/containers/c00914a60e21cceb34581232a917d832.simg
  sentieon_lic_path: /fsx/references/runtime_assets/cached_envs/Life_Sciences_Manufacturing_Corporation_eval.lic
  sentieon_tmpdir: /dev/shm/
  sentieon_install_dir: /fsx/references/runtime_assets/cached_envs/sentieon-genomics-202503.02/
