---

$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  supporting_files:
    type: object
    properties:
      mode:
        type: string
      supporting_dirs:
        type: string
      webdav_point:
        type: string
      link_root:
        type: string
      link_point:
        type: string
      link_source:
        type: string
      files:
        type: object
        huref:
          type: object
          ref:
            type: string
          rtg_tools_genome:
            type: string
          truth_data:
            type: string
          calling_regions:
            type: string
        contam:
          type: object
          ref_vcf:
            type: string
          readthrough_reportable_range_fp:
            type: string
          readthrough_reportable_range_mendeliome_fp:
            type: string
        iddnas:
          type: object
          iddnas_barcodes_fp:
            type: string
        fastv:
          type: object
          js_files:
            type: string
          kmer_collection:
            type: string
          kmer:
            type: string
          genomes:
            type: string
        octopus:
          type: object
          forest_model:
            type: string
          error_model:
            type: string
          skip_regions_f:
            type: string
      required:
      - files
  truvari_sv_benchmark:
    type: object
    properties:
      threads:
        type: integer
      mem_mb:
        type: integer
      partition:
        type: string
      env_yaml:
        type: string
      extra_args:
        type: string
      truthsets:
        type: object
        additionalProperties:
          type: object
          required:
          - alt_id
          - regions
          properties:
            alt_id:
              type: string
            regions:
              type: object
              additionalProperties:
                type: object
                required:
                - truth_vcf
                - truth_tbi
                - truth_bed
                properties:
                  truth_vcf:
                    type: string
                  truth_tbi:
                    type: string
                  truth_bed:
                    type: string
  longtr:
    type: object
    required:
    - env_yaml
    - command
    - threads
    - mem_mb
    - partition
    - aligners
    - deduper
    - catalogs
    properties:
      env_yaml:
        type: string
      command:
        type: string
      threads:
        type: integer
      mem_mb:
        type: integer
      partition:
        type: string
      aligners:
        type: array
        items:
          type: string
      deduper:
        type: string
      extra_args:
        type: string
      catalogs:
        type: object
        required:
        - all
        - diseaser
        properties:
          all:
            type: object
            required:
            - name
            - regions_bed
            properties:
              name:
                type: string
              regions_bed:
                type: string
          diseaser:
            type: object
            required:
            - name
            - regions_bed
            properties:
              name:
                type: string
              regions_bed:
                type: string

required:
    - samples
